# Generated by Django 4.2.6 on 2023-10-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
